### ISSUE TITLE
[BUG] List is not loading upon deleting last item from active list Item

### ISSUE THREAD

**Issue by shahzaib1136** [rigelglen/react-paginated-list#18]
**Describe the bug**
If we have 7 items and show 3 items per page, upon deleting the 7th item from the third page it will reset the page count to 2 from 3 but it does not show the items for the second page.

**To Reproduce**
1- get any list of 7 items 
2- set itemsPerPage={3}
3- navigate to the 3rd page then delete the last item
4- it will move to the previous page with unselected page and it will not show any page data.
**Expected behavior**
It should move toward the previous page if the currently selected page data is not available and should show items from the previous page.

**Screenshots**
https://www.loom.com/share/f3d5525ffbf34450b9da2607983c3a95

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rigelglen** [comment]
Hi @shahzaib1136 thanks for reporting the issue.

I've fixed this with 9f0eb81da479b5a12bd7f58c8ad539e8feba57e0

You can update to version 1.1.6 which has the fix for this :)
